In [101]:
import pandas as pd
pavadinimai = pd.read_csv('gatves.csv')
pavadinimai.head(100)

,_type,_id,_revision,gat_kodas,tipas,tipo_santrumpa,pavadinimas,gyvenamoji_vietove._id,nuo,gat_nuo
0,datasets/gov/rc/ar/gatve/Gatve,6a2f2a24-41e4-400a-92be-d69cce8236b0,887da2a7-8865-4504-949b-e6cd3ad0a2cc,1122775,gatvė,g.,Pyvesos,43226575-6207-4aa5-bc03-b71cf1c28bc7,2011-10-11,2011-10-11
1,datasets/gov/rc/ar/gatve/Gatve,989b45ae-a09a-4112-b72b-79cf886a93e7,29972112-dc65-4a8a-8892-e8c388425372,1123088,gatvė,g.,Saulėtekio,229c602b-cb0a-45ec-818d-42432430d096,2012-06-01,2012-06-01
2,datasets/gov/rc/ar/gatve/Gatve,1a301474-a958-49e8-bf20-aa5761b35968,c85d311f-5b76-4667-8504-af396c21a23b,1123179,gatvė,g.,Tujų,c9a461d5-933f-4d02-8519-32995f46805c,2011-07-12,2011-07-12
3,datasets/gov/rc/ar/gatve/Gatve,c96a45f4-bb0c-4125-bcf1-5cbddf2ad339,a3c884c3-8e29-4633-a261-97f956fed649,1123312,gatvė,g.,Gluosnių,38b16c85-e6be-40cb-b5c6-ab388bd9b63b,2011-07-15,2011-07-15
4,datasets/gov/rc/ar/gatve/Gatve,2e225265-4fc8-4665-a2ad-2459869b1b6e,128b3695-8d8d-479e-9a17-ca07e7ea66ec,1123331,gatvė,g.,Peršėkės,db6cdc43-f069-4973-a537-c0d37c32c4c4,2011-07-12,2011-07-12
...,...,...,...,...,...,...,...,...,...,...
95,datasets/gov/rc/ar/gatve/Gatve,81271dfa-4f3d-460d-84eb-8a481c876f2a,008668bb-32f0-4939-b7d5-cbf9c9c41379,1125812,gatvė,g.,Mokyklos,ad4daabb-a631-422e-bb9c-7c252a15f3ac,2011-07-21,2011-07-21
96,datasets/gov/rc/ar/gatve/Gatve,568e8ad0-71fd-42df-bfbd-fdf2a3ec3774,0a788efa-2e71-4cc9-aed4-4f1adeab86f8,1125899,gatvė,g.,Ilgės,720d1ffc-a982-48ff-ad89-adc393bb747c,2011-10-11,2011-10-11
97,datasets/gov/rc/ar/gatve/Gatve,37b848b6-0abd-437a-a160-58bd7b877740,fb26b3e9-f86d-4b1c-b73e-89b951fc7494,1126053,gatvė,g.,Lauko,325027c7-caa9-427a-8423-670f4750b7b0,2011-10-11,2011-10-11
98,datasets/gov/rc/ar/gatve/Gatve,d5b77392-0fcc-457a-b503-f779dcd65df3,0498ec01-6bdf-4155-9d16-18b31d55d507,1126072,gatvė,g.,Dvaro,5659612c-bb30-4d84-86be-c560f7531dfa,2011-10-11,2011-10-11
99,datasets/gov/rc/ar/gatve/Gatve,cf4e685d-390d-4a73-87bf-55ab12e10105,f1975d62-cb55-495a-b143-d632e84b5b64,1126474,gatvė,g.,Pamiškės,2d237d78-c881-4315-9fdf-c23a4bb97e4f,2012-06-01,2012-06-01

Išsiaiškiname kokie yra stulpelių tikslūs pavadinimai:

In [102]:
pavadinimai.columns.values.tolist()

['_type',
 '_id',
 '_revision',
 'gat_kodas',
 'tipas',
 'tipo_santrumpa',
 'pavadinimas',
 'gyvenamoji_vietove._id',
 'nuo',
 'gat_nuo']

Šalinam nereikalingus analizei stulpelius:

In [103]:
pavadinimai.drop(columns=
['_type',
 '_id', 
 '_revision',
 'tipo_santrumpa',
 'nuo',
 'gat_nuo'], 
inplace=True)

Pervadinu stulpelį:

In [104]:
pavadinimai.rename(
    columns={"gyvenamoji_vietove._id": "vieta",},
    inplace=True)

In [105]:
gatves = pavadinimai
gatves.to_csv('sutvarkytos_gatves.csv', index=False)

Išsirūšiuojam pavadinimus pagal abecėlę:

In [106]:
gatves.sort_values('pavadinimas')

       gat_kodas  tipas   pavadinimas                                 vieta
6848     1235287  takas        1-asis  21bbe639-b485-490c-8ab4-e58494826b8c
35533    1625244  gatvė   1-ojo Forto  d9d35c43-4935-49da-953b-693effa947be
6849     1235291  takas        2-asis  21bbe639-b485-490c-8ab4-e58494826b8c
16956    1362823  gatvė  3-iojo Forto  c15961fc-edb3-44e7-8f6f-52813ab39bf2
6533     1231349  gatvė   9-ojo Forto  58437361-d62a-4714-9b74-f07ae0b9d66b
...          ...    ...           ...                                   ...
16347    1355222  gatvė          Žąsų  7cfc1a44-8e95-4e7d-9420-636cbe31d41f
40491    1690478  gatvė       Žėručio  2646f0bc-39a9-4770-88bd-0a53b1c9b9bf
7266     1240536  gatvė       Žėručio  2053f964-5101-4094-9eed-b4fb60754f05
11843    1299233  gatvė       Žėručio  a4e4f97d-e0c5-40f1-9660-d23cfd047428
40812    1694636  gatvė        Žūklės  ecd017de-4285-4f24-974a-9d2eacfb5eab

[58958 rows x 4 columns]

Patikrinam ar nėra nulinių ir ne skaitinių reikšmių stulpeliuose:

In [115]:
gatves.isnull().sum()

gat_kodas      0
tipas          0
pavadinimas    0
vieta          0
dtype: int64

In [116]:
gatves.isna().sum()

gat_kodas      0
tipas          0
pavadinimas    0
vieta          0
dtype: int64

Ar nėra besidubliuojančių eilučių?

In [117]:
gatves.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
58953    False
58954    False
58955    False
58956    False
58957    False
Length: 58958, dtype: bool

Bandom grupuoti pagal pavadinimus, ar pagal vietovę?

In [140]:
vietove = gatves.groupby('pavadinimas')

In [119]:
vietove

In [146]:
#naujas stulpelis su pasikartojimais
kokiu_daugiausia_gatviu = vietove.count()

Pažiūrim pirmas 5 ir paskutines 5 reikšmes pagal abecėlę.

In [147]:
kokiu_daugiausia_gatviu.head(14664)

                    gat_kodas  tipas  vieta
pavadinimas
Airėnų Sodų 3-ioji          1      1      1
Airėnų Sodų 6-oji           1      1      1
Airėnų Sodų 7-oji           1      1      1
Baluosio                    1      1      1
Beržų                       1      1      1
Ežero                       1      1      1
Gilūšio                     2      2      2
Gluosnių                    1      1      1
Grikienių                   1      1      1
Jaunystės                   1      1      1
Mokyklos                    1      1      1
Paparčių                    1      1      1
Parko                       1      1      1
Peršėkės                    1      1      1
Pievų                       1      1      1
Pijuoso                     1      1      1
Pirties                     1      1      1
Plentų                      1      1      1
Pyvesos                     2      2      2
Rasos 1-oji                 1      1      1
Rasos 2-oji                 1      1      1
Rasos 3-ioji                1      1      1
Rasos 4-oji                 1      1      1
Rasos 5-oji                 1      1      1
Rasos 7-oji                 1      1      1
Saulėtekio                  2      2      2
Semeliškių                  1      1      1
Slėnio                      1      1      1
Sodo                        1      1      1
Sudervės                    1      1      1
Taučionių                   1      1      1
Trakų                       3      3      3
Tujų                        1      1      1
Tvenkinio                   1      1      1
Verniejaus                  2      2      2
Vileišių                    1      1      1
Ąžuolo                      1      1      1
Ąžuolų                      1      1      1
Šaltinių                    1      1      1
Šušvės                      1      1      1
Švenčiaus                   1      1      1
Žiedo                       1      1      1
Žilinų                      1      1      1
Žolynų                      1      1      1

Noriu surasti ir surūšiuoti gatvių pavadinimus, kurie kartojasi daugiausia kartų. Surūšiuoti mažėjimo tvarka, kad sužinoti kokia gatvė populiariausia Lietuvoje.

In [156]:
#TOP 50 Lietuvos populiariausių gatvių.
#ir pridedu naują stulpelį
kokiu_daugiausia_gatviu['pasikartojimai'] = kokiu_daugiausia_gatviu['vieta']
#kokiu_daugiausia_gatviu.head(50)
kokiu_daugiausia_gatviu.sort_values(by='pasikartojimai', ascending=False)

                    gat_kodas  tipas  vieta  pasikartojimai
pavadinimas
Trakų                       3      3      3               3
Verniejaus                  2      2      2               2
Saulėtekio                  2      2      2               2
Pyvesos                     2      2      2               2
Gilūšio                     2      2      2               2
Tvenkinio                   1      1      1               1
Semeliškių                  1      1      1               1
Slėnio                      1      1      1               1
Sodo                        1      1      1               1
Sudervės                    1      1      1               1
Taučionių                   1      1      1               1
Tujų                        1      1      1               1
Airėnų Sodų 3-ioji          1      1      1               1
Rasos 5-oji                 1      1      1               1
Vileišių                    1      1      1               1
Ąžuolo                      1      1      1               1
Ąžuolų                      1      1      1               1
Šaltinių                    1      1      1               1
Šušvės                      1      1      1               1
Švenčiaus                   1      1      1               1
Žiedo                       1      1      1               1
Žilinų                      1      1      1               1
Rasos 7-oji                 1      1      1               1
Rasos 4-oji                 1      1      1               1
Airėnų Sodų 6-oji           1      1      1               1
Rasos 3-ioji                1      1      1               1
Airėnų Sodų 7-oji           1      1      1               1
Baluosio                    1      1      1               1
Beržų                       1      1      1               1
Ežero                       1      1      1               1
Gluosnių                    1      1      1               1
Grikienių                   1      1      1               1
Jaunystės                   1      1      1               1
Mokyklos                    1      1      1               1
Paparčių                    1      1      1               1
Parko                       1      1      1               1
Peršėkės                    1      1      1               1
Pievų                       1      1      1               1
Pijuoso                     1      1      1               1
Pirties                     1      1      1               1
Plentų                      1      1      1               1
Rasos 1-oji                 1      1      1               1
Rasos 2-oji                 1      1      1               1
Žolynų                      1      1      1               1

In [157]:
#kokių daugiausia gatvių
#pop_gatves = kokiu_daugiausia_gatviu[kokiu_daugiausia_gatviu['gat_kodas']>1.9].value_counts(sort=True)

In [161]:
#top_50.to_csv('top50_gatves.csv', index=False)
#top_50 = pd.read_csv('top50_gatves.csv')

#sns.set_theme(style="darkgrid")

# Load an example dataset with long-form data
#top_50 = sns.load_dataset('top50_gatves.csv')

# Plot the responses for different events and regions
#sns.lineplot(x="pavadinimas", y="vieta",
          #   hue="region", style="event",
          #   data=top_50)

In [ ]:
#sns.lineplot(data=top_50, x="pavadinimas", y="vieta")